config/routes.rb
Rails.application.routes.draw do

  root 'jobs#index'
  resources :jobs

end

app/models/category.rb
class Category < ActiveRecord::Base
	 has_many :jobs
end

app/models/job.rb
class Job < ActiveRecord::Base
	belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	def index
		@jobs = Job.all
	end

	def new
		@job = Job.new
		@categories =  Category.all.map{|category| category.name}
	end

	def create 
		Job.create(job_params)
  	redirect_to jobs_path
	end

	def edit
		@job = Job.find(params[:id])
	end

	def update
		@job = Job.find(params[:id])
		@job.update_attributes(job_params)
		redirect_to jobs_path
	end

	def destroy
		@job = Job.find(params[:id])
		@job.destroy
		redirect_to jobs_path
	end

	def filter 

	end

	private

	def job_params
		params.require(:job).permit(:title, :description, :category_id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for @job do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description, size: '60x6' %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Edit Posting</h1>

<%= render 'form' %>

app/views/jobs/index.html.erb
<div class="container-fluid">
	<h1>Weekender Jobs</h1>



	<div class="row">
			<div class="col-sm-9">
			<div class="btn-group btn-group-justified" role="group" aria-label="Justified button group with nested dropdown">
	      <a href="#"  role="button">Front-End Development</a>
	      

	      <%#= link_to "Front-End Development", "http://www.google.com" , class: "btn btn-default"  %>
	      <%= form_tag("/jobs", method: "get")  do %>
	         <%= check_box_tag 'category[]', "frontend" %>
	         <%= label_tag(:pet_dog, "Front-End Development") %>

	         <%= check_box_tag 'category[]', "backend" %>
	         <%= label_tag(:pet_dog, "Back-End Development") %>

	        <%= check_box_tag 'category[]', "ui" %>
	        <%= label_tag(:pet_dog, "UI Design") %>

	        <%= check_box_tag 'category[]', "app" %>
	        <%= label_tag(:pet_dog, "App Development") %>

	        <%= submit_tag 'Submit' %>
	      <% end %>

	    </div>
			<table class="table table-striped">
			  <thead>
			<!--     <tr>
			      <th>#</th>
			      <th>Title</th>
			      <th></th>
			      <th></th>
			    </tr> -->
			  </thead>

				
			  <tbody>
			    <% @jobs.each do |job| %>
			    <tr>
			      <th scope="row">1</th>
			      <td><h3><%=job.title %></h3></td>
			      <td><p><%=job.description %></p></td>
			      <td><h5><%= link_to "Edit Posting", edit_job_path(job)%></h5></td>
			    	<td><h5><%= link_to 'Delete Posting', job, method: :delete %></h5></td>
			    	<td>New York City</td>
			    	<td>Flex</td>
			    </tr>
			    <% end %>
			   
			  </tbody>
			</table>
		</div>

		<div class="col-sm-3">
			<button>Post a Job</button>
		</div>
		
	</div>
</div>

app/views/jobs/new.html.erb
<h1>Add a Job</h1>

<%= form_for @job do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description, size: '60x6' %>
  </div>

  <div>
    <%= select_tag(:category_id, options_for_select(@categories)) %>
    <%= f.text_area :category_id %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Weekender</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<header>
	  <div class="left-nav">
	    <ul>
	      <li><%= link_to "Home", jobs_path %></li>
	    </ul>
	  </div>
	  <div class="right-nav">
	    <ul>
	      <li><%= link_to "Add Job", new_job_path %></li>
	    </ul>
	  </div>
	  <div class="clearfix"></div>
	</header>
	<%= yield %>

</body>
</html>